# Generated by scripts/generate_sr_limits.py; do not edit.
LIMITS = {'min_side': 64, 'input_max_side': 1920, 'input_max_pixels': 2073600, 'output_max_side': 16384, 'cxr_max_payload': 134217728, 'output_header_bytes': 8, 'output_bytes_per_pixel': 8, 'output_max_pixels': 16777215}
