"""Bounded generated storage; destructive operations accept inventory IDs, never paths."""
from __future__ import annotations

import contextlib
from contextvars import ContextVar
from functools import wraps
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import threading
import time

GiB = 1024 ** 3
MiB = 1024 ** 2
DEFAULTS = {"cache_gib": 2, "temporary_gib": 8, "job_gib": 2,
            "entry_mib": 128, "free_gib": 2}
LOCK = threading.RLock()
_jobs = {}
_current = ContextVar("dlss_storage_job", default=None)
_hash = re.compile(r"[0-9a-f]{64}(?:\.partial-[0-9a-f]{32})?")
_job = re.compile(r"(?:render-)?[0-9a-f]{32}")


def settings(root):
    path = Path(root) / "storage-policy.json"
    return validate(json.loads(path.read_text())) if path.is_file() else dict(DEFAULTS)


def validate(value):
    if not isinstance(value, dict) or set(value) != set(DEFAULTS):
        raise ValueError("Invalid storage settings")
    for key, maximum in (("cache_gib", 1024), ("temporary_gib", 2048), ("job_gib", 1024),
                         ("entry_mib", 512), ("free_gib", 1024)):
        if type(value[key]) is not int or not 1 <= value[key] <= maximum:
            raise ValueError(f"Invalid storage limit: {key}")
    if value["job_gib"] > value["temporary_gib"]:
        raise ValueError("Per-job limit must not exceed total temporary limit")
    return dict(value)


def tree_size(path):
    """Do not follow any symlink. Include every regular generated byte."""
    path = Path(path)
    if path.is_symlink():
        return 0
    if path.is_file():
        return path.stat().st_size
    total = 0
    for parent, dirs, files in os.walk(path, followlinks=False):
        dirs[:] = [d for d in dirs if not (Path(parent) / d).is_symlink()]
        for name in files:
            file = Path(parent) / name
            try:
                if not file.is_symlink():
                    total += file.stat().st_size
            except FileNotFoundError:
                pass
    return total


def _busy():
    from .execution_log import _active, _lock
    with _lock:
        return bool(_active)


def _entries(root, temp):
    for category, parent, pattern in (("prepared", Path(root) / "prepared-clips", _hash),
                                      ("temporary", Path(temp) / "dlss-experimental", _job),
                                      ("execution", Path(root) / "executions", re.compile(r"[0-9a-f]{32}\.json"))):
        if parent.is_symlink() or not parent.is_dir():
            continue
        for path in parent.iterdir():
            if not pattern.fullmatch(path.name) or path.is_symlink() or not (path.is_file() if category == "execution" else path.is_dir()):
                continue
            try:
                st = path.stat()
                # The inode/mtime fingerprint prevents old UI selections deleting a replacement.
                ident = hashlib.sha256(f"{category}:{path.resolve()}:{st.st_dev}:{st.st_ino}:{st.st_mtime_ns}".encode()).hexdigest()
                yield category, path, ident, st
            except FileNotFoundError:
                pass


def _file_list(path):
    if path.is_file():
        return [{"name": path.name, "bytes": path.stat().st_size}], False
    files = []
    for parent, dirs, names in os.walk(path, followlinks=False):
        dirs[:] = [d for d in dirs if not (Path(parent) / d).is_symlink()]
        for name in names:
            file = Path(parent) / name
            if file.is_symlink():
                continue
            if len(files) >= 256:
                return files, True
            try:
                files.append({"name": str(file.relative_to(path)), "bytes": file.stat().st_size})
            except FileNotFoundError:
                pass
    return files, False


def inventory(root=None, temp=None):
    if root is None:
        from .config import data_root
        root = data_root()
    if temp is None:
        import folder_paths
        temp = Path(folder_paths.get_temp_directory())
    with LOCK:
        busy = _busy()
        entries = []
        for category, path, ident, st in _entries(root, temp):
            files, truncated = _file_list(path)
            entries.append({"id": ident, "kind": category, "name": path.name,
                            "path": str(path), "bytes": tree_size(path), "modified": st.st_mtime,
                            "files": files, "files_truncated": truncated,
                            "removable": not busy,
                            "state": "protected_during_execution" if busy else "idle"})
        entries.sort(key=lambda x: x["modified"], reverse=True)
        return {"checked_at": time.time(), "busy": busy, "settings": settings(root),
                "roots": {"prepared": str(Path(root) / "prepared-clips"),
                          "temporary": str(Path(temp) / "dlss-experimental"),
                          "execution": str(Path(root) / "executions")},
                "entries": entries, "bytes": sum(x["bytes"] for x in entries),
                "scope": "Prepared entries, execution records and Comfy DLSS temporary jobs, including preview media and job logs. Saved outputs, source media, DLLs, snapshots and Proton prefixes are excluded."}


def remove_entries(ids, root=None, temp=None):
    if not isinstance(ids, list) or not 1 <= len(ids) <= 200 or any(not isinstance(i, str) or not re.fullmatch(r"[0-9a-f]{64}", i) for i in ids):
        raise ValueError("Select 1–200 inventory IDs")
    if root is None:
        from .config import data_root
        root = data_root()
    if temp is None:
        import folder_paths
        temp = Path(folder_paths.get_temp_directory())
    # Same lock as execution admission; no new execution starts during deletion.
    with LOCK:
        if _busy() or _jobs:
            raise ValueError("Rendering is active; cleanup is available when all DLSS jobs are idle")
        current = {ident: path for _, path, ident, _ in _entries(root, temp)}
        if not set(ids) <= current.keys():
            raise ValueError("Inventory changed; refresh before deleting")
        removed = []
        for ident in dict.fromkeys(ids):
            path = current[ident]
            size = tree_size(path)
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()
            removed.append({"id": ident, "bytes": size})
        return {"removed": removed, "reclaimed_bytes": sum(x["bytes"] for x in removed)}


def save_settings(value):
    from .config import data_root
    value = validate(value)
    with LOCK:
        if _busy() or _jobs:
            raise ValueError("Change storage limits after rendering finishes")
        root = data_root()
        root.mkdir(parents=True, exist_ok=True)
        temporary = root / "storage-policy.partial"
        temporary.write_text(json.dumps(value, indent=2), encoding="utf-8")
        temporary.replace(root / "storage-policy.json")
    return value


def prune_execution_records(root, keep=1000):
    directory = Path(root) / "executions"
    with LOCK:
        if not directory.is_dir() or directory.is_symlink():
            return
        files = sorted((p for p in directory.iterdir() if p.is_file() and not p.is_symlink()
                        and re.fullmatch(r"[0-9a-f]{32}\.json", p.name)), key=lambda p: p.stat().st_mtime, reverse=True)
        for file in files[keep:]:
            file.unlink(missing_ok=True)


def make_cache_room(root, required, protected=()):
    """Caller holds the cache lock. Evict least-recently-used, inactive entries."""
    with LOCK:
        limit = settings(root)["cache_gib"] * GiB
        entries = []
        parent = Path(root) / "prepared-clips"
        if parent.is_symlink():
            raise ValueError("Prepared cache root must not be a symlink")
        if parent.is_dir():
            for p in parent.iterdir():
                if p.is_dir() and not p.is_symlink() and _hash.fullmatch(p.name):
                    entries.append((p.stat().st_mtime_ns, p, tree_size(p)))
        total = sum(e[2] for e in entries)
        protected = {Path(p).resolve() for p in protected}
        for _, path, size in sorted(entries):
            if total + required <= limit:
                break
            if path.resolve() not in protected:
                shutil.rmtree(path)
                total -= size
        if total + required > limit:
            raise ValueError("Prepared cache quota is occupied by active entries; retry after they finish")


def current_job():
    return _current.get()


def attach_job(path):
    state = current_job()
    if state is not None:
        state["path"] = Path(path)


def check_job(extra=0):
    state = current_job()
    if state is None or state["path"] is None:
        return
    used = tree_size(state["path"])
    state["peak_bytes"] = max(state["peak_bytes"], used)
    if used + extra > state["budget"]:
        raise ValueError("DLSS temporary job limit reached; use Storage Manager to raise it or choose a shorter range")
    free = shutil.disk_usage(state["path"]).free
    if free < extra + state["settings"]["free_gib"] * GiB:
        raise ValueError("DLSS stopped before consuming the configured disk free-space reserve")


def file_allowance():
    state = current_job()
    if state is None:
        return 2 * GiB
    check_job()
    return max(0, state["budget"] - tree_size(state["path"]) - 16 * MiB)


def managed_job(function):
    @wraps(function)
    def call(**kwargs):
        from .config import data_root
        from .execution_log import current_trace
        import folder_paths
        root, temp = data_root(), Path(folder_paths.get_temp_directory())
        with LOCK:
            policy = settings(root)
            used = tree_size(temp / "dlss-experimental")
            reserved = sum(s["budget"] for s in _jobs.values())
            budget = policy["job_gib"] * GiB
            if used + reserved + budget > policy["temporary_gib"] * GiB:
                raise ValueError("DLSS temporary storage quota reached. Save needed results, then remove old jobs in DLSS Storage Manager.")
            state = {"path": None, "budget": budget, "settings": policy, "peak_bytes": 0}
            _jobs[id(state)] = state
        token = _current.set(state)
        try:
            return function(**kwargs)
        finally:
            trace = current_trace()
            if trace:
                trace.record["storage_usage"] = {"job_limit_bytes": budget, "sampled_peak_bytes": state["peak_bytes"],
                                                 "temporary_limit_bytes": policy["temporary_gib"] * GiB}
            _current.reset(token)
            with LOCK:
                _jobs.pop(id(state), None)
    return call
