// Generated by scripts/generate_sr_limits.py; edit sidecar/protocol/sr_limits.json.
#pragma once
#include <cstdint>
namespace comfy_dlss::sr::limits {
inline constexpr std::uint32_t min_side = 64;
inline constexpr std::uint32_t input_max_side = 1920;
inline constexpr std::uint32_t input_max_pixels = 2073600;
inline constexpr std::uint32_t output_max_side = 16384;
inline constexpr std::uint32_t cxr_max_payload = 134217728;
inline constexpr std::uint32_t output_header_bytes = 8;
inline constexpr std::uint32_t output_bytes_per_pixel = 8;
inline constexpr std::uint32_t output_max_pixels = 16777215;
}
