"""Generate native and packaged Python budgets from one canonical JSON."""
import json
from pathlib import Path


def values_for(root):
    values=json.loads((root/'sidecar/protocol/sr_limits.json').read_text())
    if any(type(value) is not int or value <= 0 for value in values.values()):
        raise ValueError('Transport limits must be positive integers')
    # CXR1 RESULT is PTS uint64 followed by tightly packed RGBA16F.
    # Do not replace this with a named display resolution or a tolerance percent.
    values['output_max_pixels'] = (values['cxr_max_payload'] - values['output_header_bytes']) // values['output_bytes_per_pixel']
    return values


def render(root):
    values=values_for(root)
    return ('// Generated by scripts/generate_sr_limits.py; edit sidecar/protocol/sr_limits.json.\n'
        '#pragma once\n#include <cstdint>\nnamespace comfy_dlss::sr::limits {\n'+
        ''.join(f'inline constexpr std::uint32_t {key} = {value};\n' for key,value in values.items())+'}\n')


def render_python(root):
    values=values_for(root)
    return '# Generated by scripts/generate_sr_limits.py; do not edit.\nLIMITS = '+repr(values)+'\n'


if __name__=='__main__':
    root=Path(__file__).resolve().parents[1]
    (root/'sidecar/src/sr_limits.hpp').write_text(render(root))
    (root/'comfy_dlss_experimental/_sr_limits.py').write_text(render_python(root))
